name: Unzip

on:
  push:
    paths:
      - 'woocommerce-printful-server.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Unzip
        run: |
          unzip woocommerce-printful-server.zip
          git add .
          git commit -m "Unzipped files"
          git push
